# Dependabot configuration files that automate our dependency updates by creating pull requests.
# The PRs are labeled and grouped by package ecosystem and semver update type.
# We intentionally use grouping and pull request limits to avoid creating too many PRs and
# exhausting the number of available pull requests in Lagoon.
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 2
    groups:
      minor-github-actions-dependencies:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: weekly
      timezone: Europe/Copenhagen
    labels:
      - "dependencies"
      - "github_actions"
