# Dependabot configuration files that automate our dependency updates by creating pull requests.
# The PRs are labeled and grouped by package ecosystem and semver update type.
# We intentionally use grouping and pull request limits to avoid creating too many PRs and
# exhausting the number of available pull requests in Lagoon.
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # The maximum number of pull requests for version updates
    open-pull-requests-limit: 20
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Copenhagen
    versioning-strategy: increase
    labels:
      - "dependencies"
    groups:
      radix-ui:
        patterns:
          - "@radix-ui/*"
      graphql-codegen:
        patterns:
          - "@graphql-codegen/*"
      typescript:
        patterns:
          - "typescript"
          - "tsx"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      next:
        patterns:
          - "next"
          - "@next/env"
          - "next-themes"
          - "eslint-config-next"
          - "@next/eslint-plugin-next"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "tailwindcss-animate"
      prettier:
        patterns:
          - "prettier"
          - "eslint-config-prettier"
      cva:
        patterns:
          - "class-variance-authority"
          - "clsx"
      tailwind-merge:
        patterns:
          - "tailwind-merge"
          - "prettier-plugin-merge"
          - "prettier-plugin-tailwindcss"
          - "prettier-plugin-classnames"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "@chromatic-com/storybook"
          - "eslint-plugin-storybook"
      xstate:
        patterns:
          - "xstate"
          - "@xstate/*"
      vite:
        patterns:
          - "vitest"
          - "vite-tsconfig-paths"
          - "@vitejs/plugin-react"
      react-query:
        patterns:
          - "@tanstack/react-query"
          - "@tanstack/react-query-devtools"
      jwt-simple:
        patterns:
          - "jwt-simple"
          - "@types/jwt-simple"
      cypress:
        patterns:
          - "cypress"
          - "eslint-plugin-cypress"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    # The maximum number of pull requests for version updates
    open-pull-requests-limit: 20
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
      day: monday
      time: "04:00"
      timezone: Europe/Copenhagen
    labels:
      - dependencies
      - github_actions
