# Dependabot configuration files that automate our dependency updates by creating pull requests.
# The PRs are labeled and grouped by package ecosystem and semver update type.
# We intentionally use grouping and pull request limits to avoid creating too many PRs and
# exhausting the number of available pull requests in Lagoon.
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # The maximum number of pull requests for version updates
    open-pull-requests-limit: 10
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: weekly
      timezone: Europe/Copenhagen
    labels:
      - "dependencies"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    # The maximum number of pull requests for version updates
    open-pull-requests-limit: 10
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - github_actions
