# Workflow name
name: "Chromatic"

# Event for the workflow
on:
  push:
    branches:
      - main
    paths:
      - "**.css"
      - "**.js"
      - "**.tsx"
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "**.css"
      - "**.js"
      - "**.tsx"

# List of jobs
jobs:
  chromatic-deployment:
    name: Chromatic

    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests.
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvrmc"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
